### ISSUE TITLE
[Suggestion]: ko.react.dev 공식레포

### ISSUE THREAD

**Issue by Yaminyam** [roy-jung/react.dev.ko#277]
### Summary

https://github.com/reactjs/ko.react.dev
위 레포와 차이가 뭔가요?
더욱 많은 사람들이 접할수있게 공식레포에 기여하는게 좋다고 생각됩니다!

### Details

위와 같음.

**Comment by roy-jung** [comment]
여기는 공식레포가 번역을 착수하기 한참 전에 스터디하면서 작업한 공간입니다.
공식레포와의 차이라면,

- 스터디 멤버들 주도로 번역한 '사적이고 비공식적인' 사이트
- 각 페이지마다 스터디 영상 기재
- 원문과 번역글을 함께 기재
- 번역 외에 추가로 참고할 만한 내용을 소개한 경우도 있음
- 페이지마다 코멘트로 질문이나 토론 가능

등이 있겠습니다.
