### ISSUE TITLE
9-2. flushSync

### ISSUE THREAD

**Issue by roy-jung** [roy-jung/react.dev.ko#46]

**Comment by samseburn** [comment]
@ryungom @roy-jung 혹시 해당 문서 웹 동기화 작업 아직 진행하지 않았다면 작업해도 될까요?

**Comment by ryungom** [comment]
@samseburn 앗 아뇨~ 제가 내일 진행하려고 했습니다ㅎㅎ 괜찮습니다

**Comment by ryungom** [comment]
@samseburn 진행상황을 보니 내일 해당부분 나가겠네요...ㅎㅎ 제가 지금부터 하겠습니다
